Assignment 19 baru tampilan
webprogramminghack/assignment-class19 pull request #3
Opened 2024-11-04 14:56 UTC by novelyr

pak mohon arahan terkait langkah selanjutnya

2025-01-09 10:49 UTC, webprogramminghack requested changes
Cek video berikut
https://www.awesomescreenshot.com/video/35354110?key=c8a2b4144900e8e1311894fd436628c3

2025-01-09 10:49 UTC, webprogramminghack commented on src/component/Input/Input.module.scss
> +}
Tambahkan padding, agar ketika dimasukkan teks, maka tidak menempel dengan border

2025-01-10 01:51 UTC, novelyr commented on src/component/Input/Input.module.scss
> +}
sudah pak

2025-01-10 01:51 UTC, novelyr commented
> Cek video berikut https://www.awesomescreenshot.com/video/35354110?key=c8a2b4144900e8e1311894fd436628c3

sudah saya perbaiki fungsinya ya pak

2025-01-13 06:55 UTC, webprogramminghack approved these changes
Assignment completed, good job

2025-01-13 06:55 UTC, closed without merging